'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import { fmtShort } from '@/lib/utils';
import { useStore } from '@/lib/store';
import { useLiveTimers } from '@/lib/useLiveTimer';
import { EditTaskDrawer } from './EditTaskDrawer';
import type { PlannedBlock, TrackedSession } from '@/types';

// Feature 1 — Gantt-style horizontal day view.
//
// Two tracks:
//  • Planned (top, lighter) — planned_blocks for the day
//  • Actual  (bottom, solid) — tracked_sessions for the day
//
// X-axis is auto-bounded by the data: 1h before earliest entry to
// max(now, last entry + 1h), with an 8h minimum window so a single 41m
// session doesn't render as an unreadable thumbnail.

interface Props {
  dayStart: Date;
  plannedBlocks: PlannedBlock[];
  sessions: TrackedSession[];
  highlightSessionId?: string | null;
  onHighlightClear?: () => void;
  // Called after an Adjust/Delete so the parent can refetch sessions. Optional
  // because TimelineGantt is also rendered in places that pull from the store.
  onSessionsChanged?: () => void;
}

const HOUR_MS = 3600 * 1000;
const DAY_MS = 24 * HOUR_MS;
const PX_PER_HOUR = 120; // fixed horizontal scale → full day is 2880px wide
const DAY_WIDTH_PX = 24 * PX_PER_HOUR;
const LEFT_GUTTER = 36;
const TRACK_HEIGHT = 28;
const PLANNED_TRACK_TOP = 36;
const ACTUAL_TRACK_TOP = 76;
const MIN_BLOCK_PX = 32; // spec: minimum block width 32px on mobile

interface BlockMeta {
  id: string;
  taskId: string | null;
  title: string;
  subtitle: string;
  startMs: number;
  endMs: number;
  color: string;
  // New-spec-1 Feature 4 — which sub-lane inside the Actual track this block
  // lives in. Single lane when nothing overlaps; auto-stacked when it does.
  lane?: number;
  // Phase 4 — true when the underlying tracked_sessions row was created or
  // edited retroactively. Drives the small ✎ badge so the user can see at a
  // glance which blocks are auto-tracked vs hand-entered.
  manuallyEntered?: boolean;
  // Phase 4 — true for block_type='break' rows, so we can paint them with the
  // striped lavender pattern from the demo HTML.
  isBreak?: boolean;
  breakLabel?: string | null;
  // Phase 5 — synthetic gap-block (no DB row yet). Set when generated by the
  // gap-detection algorithm. Click → open the LabelGapModal which inserts a
  // real break row.
  isAutoGap?: boolean;
  // Suggested label from the time-of-day heuristic; user confirms or relabels.
  suggestedLabel?: string | null;
}

// Phase 5 — time-of-day heuristic for auto-labelling unrecorded gaps. Returns
// the suggested label (one of BREAK_LABELS' ids, or null if nothing fits).
// Lunch window: 12:00-14:00 local. Walk/break windows: 6-9 and 17-19.
// Anything else: no suggestion (label stays null until the user picks).
function suggestBreakLabel(midpointMs: number): string | null {
  const d = new Date(midpointMs);
  const hour = d.getHours();
  if (hour >= 12 && hour < 14) return 'lunch';
  if ((hour >= 6 && hour < 9) || (hour >= 17 && hour < 19)) return 'walk';
  return null;
}

// Phase 5 — find unrecorded gaps between consecutive TRACKED sessions on the
// current day. Excludes break rows (they're already labelled) and ignores
// gaps shorter than `minGapMinutes`. Returns synthetic BlockMeta entries
// flagged isAutoGap so the renderer treats them differently.
//
// The window-clip arg lets the caller cap the gap end at "now" for today —
// otherwise we'd paint a gigantic gap from the last session end to midnight
// every time the user opens the page partway through the day.
function detectGapBlocks(args: {
  sessions: TrackedSession[];
  windowStartMs: number;
  windowEndMs: number;
  minGapMinutes: number;
  clipToMs: number; // upper bound for the last gap's end
}): BlockMeta[] {
  const { sessions, windowStartMs, windowEndMs, minGapMinutes, clipToMs } =
    args;
  const minGapMs = minGapMinutes * 60 * 1000;
  // Only closed, non-break sessions contribute to the timeline of "work that
  // actually happened." Live timers and break rows are excluded.
  const tracked = sessions
    .filter((s) => s.ended_at && s.block_type !== 'break')
    .map((s) => ({
      start: new Date(s.started_at).getTime(),
      end: new Date(s.ended_at as string).getTime(),
    }))
    .filter((s) => s.end > windowStartMs && s.start < windowEndMs)
    .sort((a, b) => a.start - b.start);

  const out: BlockMeta[] = [];
  for (let i = 0; i < tracked.length - 1; i++) {
    const gapStart = tracked[i].end;
    const gapEnd = Math.min(tracked[i + 1].start, clipToMs);
    if (gapEnd - gapStart < minGapMs) continue;
    const mid = gapStart + (gapEnd - gapStart) / 2;
    const suggested = suggestBreakLabel(mid);
    out.push({
      id: `gap-${gapStart}`,
      taskId: null,
      title: suggested
        ? `Auto · ${suggested}`
        : 'Unrecorded gap',
      subtitle: 'Click to label',
      startMs: gapStart,
      endMs: gapEnd,
      color: '#a855f7',
      isBreak: true,
      isAutoGap: true,
      breakLabel: null,
      suggestedLabel: suggested,
    });
  }
  return out;
}

export function TimelineGantt({
  dayStart,
  plannedBlocks,
  sessions,
  highlightSessionId,
  onHighlightClear,
  onSessionsChanged,
}: Props) {
  const tasks = useStore((s) => s.tasks);
  const tags = useStore((s) => s.tags);
  const activeSessions = useStore((s) => s.activeSessions);
  const elapsedMap = useLiveTimers();
  const updateSessionTimes = useStore((s) => s.updateSessionTimes);
  const deleteSession = useStore((s) => s.deleteSession);
  const addSession = useStore((s) => s.addSession);
  const addPlannedBlock = useStore((s) => s.addPlannedBlock);
  const stopSession = useStore((s) => s.stopSession);
  // Phase 5 — gap-detection toggles. Defaults match the migration so missing
  // prefs (first signed-in render before fetchPrefs lands) behave identically
  // to the user-default state.
  const prefs = useStore((s) => s.prefs);
  const [editingSessionId, setEditingSessionId] = useState<string | null>(null);
  const [addOpen, setAddOpen] = useState(false);
  // Phase 5 — gap currently being labelled. Storing the meta directly (not
  // an id) because synthetic gaps have no DB row yet — they're regenerated on
  // every render from the day's tracked sessions.
  const [labellingGap, setLabellingGap] = useState<BlockMeta | null>(null);

  // `nowMs` is sampled once and ticked every minute. Storing it as state keeps
  // every Date.now() reference out of the render body (React Compiler purity).
  const [nowMs, setNowMs] = useState<number>(() => Date.now());
  useEffect(() => {
    const id = setInterval(() => setNowMs(Date.now()), 60_000);
    return () => clearInterval(id);
  }, []);

  const [hover, setHover] = useState<{ x: number; meta: BlockMeta } | null>(null);
  const [openTaskId, setOpenTaskId] = useState<string | null>(null);
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const didCenterRef = useRef(false);

  // Build planned + actual block metadata up front so bounds + render share data.
  const plannedMeta: BlockMeta[] = useMemo(
    () =>
      plannedBlocks.map((b) => {
        const task = tasks.find((t) => t.id === b.task_id);
        const color =
          (task?.tag_ids[0] && tags.find((x) => x.id === task.tag_ids[0])?.color) ||
          '#1a1a2e';
        const start = new Date(b.start_at).getTime();
        return {
          id: `p-${b.id}`,
          taskId: b.task_id,
          title: task?.title ?? 'Planned block',
          subtitle: `${fmtShort(b.duration_seconds)} planned`,
          startMs: start,
          endMs: start + b.duration_seconds * 1000,
          color,
        };
      }),
    [plannedBlocks, tasks, tags],
  );

  const actualMeta: BlockMeta[] = useMemo(() => {
    const liveIds = new Set(activeSessions.map((a) => a.id));
    const blocks: BlockMeta[] = [];
    for (const s of sessions) {
      const task = tasks.find((t) => t.id === s.task_id);
      const sub = task?.subtasks.find((x) => x.id === s.subtask_id);
      const start = new Date(s.started_at).getTime();
      const isLive = !s.ended_at && liveIds.has(s.id);

      // Only paint blocks for time the user actually reported:
      //  • live timer  → cap at LIVE_CAP_SECONDS. A timer left running for
      //    hours is almost always abandoned (tab open, user away). We can't
      //    tell "actually working" from "walked away", so we hard-cap the
      //    visual so untracked hours don't get painted as work.
      //  • ended session with duration_seconds → use that as-is.
      //  • orphaned session (no end, not live) → skip entirely so we don't
      //    paint a giant bar from started_at to "now".
      const LIVE_CAP_SECONDS = 45 * 60;
      let dur: number;
      if (isLive) {
        const rawElapsed = elapsedMap[s.id] ?? Math.floor((nowMs - start) / 1000);
        dur = Math.min(rawElapsed, LIVE_CAP_SECONDS);
      } else if (typeof s.duration_seconds === 'number' && s.duration_seconds > 0) {
        dur = s.duration_seconds;
      } else {
        continue;
      }

      const matchedPlanned = plannedMeta.find(
        (p) =>
          p.taskId === s.task_id &&
          start < p.endMs &&
          start + dur * 1000 > p.startMs,
      );
      let color: string;
      if (isLive) color = '#1a1a2e';
      else if (matchedPlanned) color = '#10b981';
      else color = '#a855f7';
      blocks.push({
        id: `a-${s.id}`,
        taskId: s.task_id,
        title:
          s.block_type === 'break'
            ? `Break · ${s.break_label ?? 'unlabelled'}`
            : task?.title ?? 'Deleted task',
        subtitle:
          s.block_type === 'break'
            ? s.note ?? 'Labeled break'
            : sub
              ? `→ ${sub.title}`
              : 'Whole task',
        startMs: start,
        endMs: start + dur * 1000,
        color,
        manuallyEntered: s.manually_entered,
        isBreak: s.block_type === 'break',
        breakLabel: s.break_label,
      });
    }

    // New-spec-1 Feature 4 — lane-stacking. Greedy first-fit: for each block
    // sorted by start, place it in the lowest-indexed lane whose last block
    // ended before this one starts. Overlaps spread across lanes.
    const sorted = [...blocks].sort((a, b) => a.startMs - b.startMs);
    const laneEnds: number[] = [];
    const laneOf = new Map<string, number>();
    for (const b of sorted) {
      let placed = false;
      for (let i = 0; i < laneEnds.length; i++) {
        if (laneEnds[i] <= b.startMs) {
          laneEnds[i] = b.endMs;
          laneOf.set(b.id, i);
          placed = true;
          break;
        }
      }
      if (!placed) {
        laneOf.set(b.id, laneEnds.length);
        laneEnds.push(b.endMs);
      }
    }
    return blocks.map((b) => ({ ...b, lane: laneOf.get(b.id) ?? 0 }));
  }, [sessions, tasks, plannedMeta, activeSessions, elapsedMap, nowMs]);

  // Total number of lanes the Actual track needs to accommodate overlaps.
  const actualLaneCount = useMemo(
    () => Math.max(1, ...actualMeta.map((a) => (a.lane ?? 0) + 1)),
    [actualMeta],
  );

  // Phase 5 — auto-detected gap blocks. Only painted on past days and on the
  // already-elapsed portion of today; the live timer's "now" caps it so a
  // gap doesn't run all the way to midnight.
  const showBreaks = prefs?.show_break_blocks ?? true;
  const minGapMin = prefs?.break_min_gap_minutes ?? 5;
  const gapMeta: BlockMeta[] = useMemo(() => {
    if (!showBreaks) return [];
    return detectGapBlocks({
      sessions,
      windowStartMs: dayStart.getTime(),
      windowEndMs: dayStart.getTime() + DAY_MS,
      minGapMinutes: minGapMin,
      clipToMs: Math.min(nowMs, dayStart.getTime() + DAY_MS),
    });
  }, [sessions, dayStart, nowMs, showBreaks, minGapMin]);

  // Full 24h window anchored to the day. The scroll container handles clipping;
  // the inner canvas is always DAY_WIDTH_PX wide so 1h == PX_PER_HOUR px.
  const windowStartMs = dayStart.getTime();
  const windowEndMs = windowStartMs + DAY_MS;
  const totalMs = DAY_MS;

  // Hour ticks across the full 24h window.
  const ticks = useMemo(() => {
    const out: { ms: number; label: string }[] = [];
    for (let i = 0; i <= 24; i++) {
      const t = windowStartMs + i * HOUR_MS;
      out.push({
        ms: t,
        label: new Date(t).toLocaleTimeString('en-IN', {
          hour: '2-digit',
          minute: '2-digit',
        }),
      });
    }
    return out;
  }, [windowStartMs]);

  const showNow = nowMs >= windowStartMs && nowMs <= windowEndMs;

  // Auto-center the scroll on "now" the first time the canvas mounts with a
  // valid width. Runs once per session — user scrolling thereafter is preserved.
  useEffect(() => {
    if (didCenterRef.current) return;
    const el = scrollRef.current;
    if (!el || el.clientWidth === 0) return;
    const nowPx = LEFT_GUTTER + ((nowMs - windowStartMs) / HOUR_MS) * PX_PER_HOUR;
    const target = Math.max(0, nowPx - el.clientWidth / 2);
    el.scrollLeft = target;
    didCenterRef.current = true;
  }, [nowMs, windowStartMs]);

  const xPct = (ms: number) => ((ms - windowStartMs) / totalMs) * 100;
  const xPx = (ms: number) => ((ms - windowStartMs) / HOUR_MS) * PX_PER_HOUR;

  // Width as percent, then enforce a 32px minimum after layout (via min-width).
  const renderBlock = (
    meta: BlockMeta,
    top: number,
    opacity: number,
    onClick: (() => void) | null,
    overlay = false,
    heightOverride?: number,
  ) => {
    const left = xPct(meta.startMs);
    const width = xPct(meta.endMs) - left;
    const isHighlighted = highlightSessionId && meta.id === `a-${highlightSessionId}`;
    // Phase 4 — break rows paint with a striped lavender pattern instead of
    // the solid block color. Matches the demo's gap-block visual.
    const breakBackground = meta.isBreak
      ? 'repeating-linear-gradient(45deg, #f1ecfb 0 6px, #e8e0f5 6px 12px)'
      : undefined;
    return (
      <div
        key={meta.id}
        onMouseEnter={(e) => {
          const rect = e.currentTarget.parentElement!.getBoundingClientRect();
          setHover({ x: e.clientX - rect.left, meta });
        }}
        onMouseLeave={() => setHover(null)}
        onClick={onClick ?? undefined}
        className="absolute rounded-md transition-all"
        style={{
          left: `${left}%`,
          width: `calc(${width}% )`,
          minWidth: MIN_BLOCK_PX,
          top,
          height: heightOverride ?? TRACK_HEIGHT,
          background: breakBackground ?? meta.color,
          border: meta.isBreak ? '1px dashed #c5b5e8' : undefined,
          opacity,
          cursor: onClick ? 'pointer' : 'default',
          outline: isHighlighted ? '2px solid #f59e0b' : overlay ? '1.5px solid #dc2626' : 'none',
          outlineOffset: isHighlighted ? 2 : 0,
          boxShadow: isHighlighted ? '0 4px 14px rgba(245,158,11,0.4)' : undefined,
        }}
        title={`${meta.title} • ${new Date(meta.startMs).toLocaleTimeString('en-IN', {
          hour: '2-digit',
          minute: '2-digit',
        })}–${new Date(meta.endMs).toLocaleTimeString('en-IN', {
          hour: '2-digit',
          minute: '2-digit',
        })}${meta.manuallyEntered ? ' • manually entered' : ''}`}
      >
        {/* Phase 4 — small "edited" pip on manually-entered rows.
            Positioned absolutely so it doesn't disturb the rest of the block. */}
        {meta.manuallyEntered && (
          <span
            aria-label="Manually entered"
            className="absolute top-[2px] right-[3px] text-[9px] font-bold leading-none px-[3px] py-[1px] rounded"
            style={{
              background: 'rgba(255,255,255,0.85)',
              color: '#92400e',
            }}
          >
            ✎
          </span>
        )}
        {/* Phase 5 — auto-detected gap blocks show their suggested label
            (italic per brief) plus a "Label →" hint so it reads as actionable. */}
        {meta.isAutoGap && (
          <div className="absolute inset-0 flex items-center justify-center px-1 text-[9px] font-bold leading-none text-[#5b3fc8] pointer-events-none whitespace-nowrap overflow-hidden">
            {meta.suggestedLabel ? (
              <span className="italic">
                {meta.suggestedLabel} · {fmtShort((meta.endMs - meta.startMs) / 1000)}
              </span>
            ) : (
              <span>
                {fmtShort((meta.endMs - meta.startMs) / 1000)} · Label →
              </span>
            )}
          </div>
        )}
      </div>
    );
  };

  // Empty state only when BOTH tracks empty (per spec).
  if (plannedMeta.length === 0 && actualMeta.length === 0) {
    return (
      <div className="bg-white rounded-[14px] p-6 text-center text-[#aaa] text-sm shadow-[0_1px_4px_rgba(0,0,0,0.06),0_0_0_1px_rgba(0,0,0,0.04)]">
        No data for this day. Start tracking to see your plan vs reality.
      </div>
    );
  }

  return (
    <>
      <div className="bg-white rounded-[14px] p-4 shadow-[0_1px_4px_rgba(0,0,0,0.06),0_0_0_1px_rgba(0,0,0,0.04)]">
        <div className="flex items-center justify-between mb-3">
          <div className="text-[13px] font-extrabold uppercase tracking-[0.5px] text-[#1a1a2e]">
            {dayStart.toLocaleDateString('en-IN', {
              weekday: 'long',
              day: 'numeric',
              month: 'short',
            })}
          </div>
          <div className="flex items-center gap-3 text-[10px] text-[#888] flex-wrap">
            <span className="flex items-center gap-1">
              <span className="inline-block w-3 h-2 rounded-sm bg-[#1a1a2e] opacity-30" />
              Planned
            </span>
            <span className="flex items-center gap-1">
              <span className="inline-block w-3 h-2 rounded-sm bg-[#10b981]" />
              On plan
            </span>
            <span className="flex items-center gap-1">
              <span className="inline-block w-3 h-2 rounded-sm bg-[#a855f7]" />
              Off plan
            </span>
            <span className="flex items-center gap-1">
              <span
                className="inline-block w-3 h-2 rounded-sm"
                style={{
                  background:
                    'repeating-linear-gradient(45deg, #f1ecfb 0 3px, #e8e0f5 3px 6px)',
                  border: '1px dashed #c5b5e8',
                }}
              />
              Break
            </span>
            <span className="flex items-center gap-1" title="Manually entered">
              <span className="text-[#92400e] font-bold">✎</span>
              Edited
            </span>
            <button
              type="button"
              onClick={() => setAddOpen(true)}
              className="ml-2 px-2 py-[3px] rounded-md border border-[#e5e7eb] bg-white text-[10px] font-bold text-[#1a1a2e] hover:border-[#1a1a2e] cursor-pointer"
              title="Log a session for this day"
            >
              + Add session
            </button>
          </div>
        </div>

        <div ref={scrollRef} className="overflow-x-auto">
        <div className="relative" style={{ height: 130, width: LEFT_GUTTER + DAY_WIDTH_PX }}>
          {/* Hour gridlines + labels */}
          {ticks.map((t) => (
            <div
              key={t.ms}
              className="absolute top-[24px] bottom-0 border-l border-dashed border-[#eee]"
              style={{ left: LEFT_GUTTER + xPx(t.ms) }}
            >
              <div className="absolute -top-[20px] -translate-x-1/2 text-[10px] text-[#888] whitespace-nowrap">
                {t.label}
              </div>
            </div>
          ))}

          {/* Track labels */}
          <div
            className="absolute left-0 text-[10px] font-bold uppercase tracking-[0.5px] text-[#888]"
            style={{ top: PLANNED_TRACK_TOP + TRACK_HEIGHT / 2 - 6 }}
          >
            Plan
          </div>
          <div
            className="absolute left-0 text-[10px] font-bold uppercase tracking-[0.5px] text-[#888]"
            style={{ top: ACTUAL_TRACK_TOP + TRACK_HEIGHT / 2 - 6 }}
          >
            Actual
          </div>

          {/* Track backgrounds */}
          <div
            className="absolute rounded-md bg-[#f9fafb]"
            style={{ left: LEFT_GUTTER, width: DAY_WIDTH_PX, top: PLANNED_TRACK_TOP, height: TRACK_HEIGHT }}
          />
          <div
            className="absolute rounded-md bg-[#f9fafb]"
            style={{ left: LEFT_GUTTER, width: DAY_WIDTH_PX, top: ACTUAL_TRACK_TOP, height: TRACK_HEIGHT }}
          />

          {/* The blocks themselves live in an absolute layer that respects the
              gutter under the track labels. */}
          <div className="absolute" style={{ left: LEFT_GUTTER, width: DAY_WIDTH_PX, top: 0, bottom: 0 }}>
            {plannedMeta.map((p) =>
              renderBlock(
                p,
                PLANNED_TRACK_TOP,
                0.35,
                p.taskId ? () => setOpenTaskId(p.taskId!) : null,
              ),
            )}
            {/* Phase 5 — synthetic auto-gap blocks. Rendered BEFORE real
                actuals so any (shouldn't-happen) overlap puts the real row
                on top. Each gap is clickable → opens LabelGapModal which
                inserts a real break_type='break' row on confirm. */}
            {gapMeta.map((g) =>
              renderBlock(
                g,
                ACTUAL_TRACK_TOP,
                0.85,
                () => setLabellingGap(g),
                false,
                TRACK_HEIGHT,
              ),
            )}
            {actualMeta.map((a) => {
              const planned = plannedMeta.find(
                (p) => p.taskId === a.taskId && a.startMs < p.endMs && a.endMs > p.startMs,
              );
              const overran = !!planned && a.endMs > planned.endMs;
              // Feature 4 lane-stacking: split the 28px Actual track into
              // `actualLaneCount` sub-lanes and shrink each block to fit.
              const laneHeight = TRACK_HEIGHT / actualLaneCount;
              const top = ACTUAL_TRACK_TOP + (a.lane ?? 0) * laneHeight;
              // Actual-track click opens the Adjust popover (edit/delete the
              // session). Held-down-timer accidents are the whole reason this
              // exists, so we don't route to the task drawer here.
              const sessionId = a.id.startsWith('a-') ? a.id.slice(2) : null;
              return renderBlock(
                a,
                top,
                1,
                sessionId ? () => setEditingSessionId(sessionId) : null,
                overran,
                laneHeight,
              );
            })}

            {/* Feature 4 — 2×/3× badge on the Actual track when we were
                multi-tasking, anchored at the left of the overlap region. */}
            {actualLaneCount > 1 && (
              <div
                className="absolute text-[9px] font-extrabold uppercase tracking-[0.5px] text-white bg-[#a855f7] rounded-md px-[5px] py-[1px]"
                style={{
                  top: ACTUAL_TRACK_TOP - 14,
                  left: 0,
                }}
                title={`Up to ${actualLaneCount} timers ran concurrently`}
              >
                {actualLaneCount}× multitasking
              </div>
            )}

            {/* "Now" line */}
            {showNow && (
              <div
                className="absolute top-[24px] bottom-0 w-[2px] bg-[#dc2626] pointer-events-none"
                style={{ left: `${xPct(nowMs)}%` }}
              >
                <div className="absolute -top-[4px] -left-[3px] w-2 h-2 rounded-full bg-[#dc2626]" />
              </div>
            )}

            {/* Tooltip */}
            {hover && (
              <div
                className="absolute z-20 pointer-events-none bg-[#1a1a2e] text-white text-[11px] rounded-md px-2 py-1 shadow-lg"
                style={{
                  left: Math.min(hover.x, 1000),
                  top: ACTUAL_TRACK_TOP + TRACK_HEIGHT + 6,
                  whiteSpace: 'nowrap',
                  transform: 'translateX(-50%)',
                }}
              >
                <div className="font-bold">{hover.meta.title}</div>
                <div className="opacity-80">{hover.meta.subtitle}</div>
                <div className="opacity-70">
                  {new Date(hover.meta.startMs).toLocaleTimeString('en-IN', {
                    hour: '2-digit',
                    minute: '2-digit',
                  })}{' '}
                  –{' '}
                  {new Date(hover.meta.endMs).toLocaleTimeString('en-IN', {
                    hour: '2-digit',
                    minute: '2-digit',
                  })}{' '}
                  · {fmtShort(Math.round((hover.meta.endMs - hover.meta.startMs) / 1000))}
                </div>
              </div>
            )}
          </div>
        </div>
        </div>

        {highlightSessionId && (
          <div className="mt-3 text-right">
            <button
              onClick={onHighlightClear}
              className="text-[11px] text-[#888] hover:text-[#1a1a2e] bg-transparent border-0 cursor-pointer"
            >
              Clear highlight
            </button>
          </div>
        )}
      </div>

      {openTaskId && (
        <EditTaskDrawer
          key={openTaskId}
          taskId={openTaskId}
          onClose={() => setOpenTaskId(null)}
        />
      )}

      {editingSessionId && (
        <AdjustSessionModal
          session={
            sessions.find((s) => s.id === editingSessionId) ??
            activeSessions.find((s) => s.id === editingSessionId) ??
            null
          }
          taskTitle={
            (() => {
              const sess =
                sessions.find((s) => s.id === editingSessionId) ??
                activeSessions.find((s) => s.id === editingSessionId);
              return tasks.find((t) => t.id === sess?.task_id)?.title ?? 'Session';
            })()
          }
          onClose={() => setEditingSessionId(null)}
          onStopLive={async () => {
            await stopSession(editingSessionId);
            setEditingSessionId(null);
            onSessionsChanged?.();
          }}
          onSave={async (startedAt, endedAt, opts) => {
            await updateSessionTimes(editingSessionId, startedAt, endedAt, {
              breakLabel: opts.breakLabel,
              note: opts.note,
            });
            setEditingSessionId(null);
            onSessionsChanged?.();
          }}
          onDelete={async () => {
            await deleteSession(editingSessionId);
            setEditingSessionId(null);
            onSessionsChanged?.();
          }}
        />
      )}

      {addOpen && (
        <AddSessionModal
          dayStart={dayStart}
          tasks={tasks.map((t) => ({ id: t.id, title: t.title }))}
          onClose={() => setAddOpen(false)}
          onAdd={async (taskId, startedAt, endedAt, opts) => {
            await addSession(taskId, startedAt, endedAt, {
              blockType: opts.blockType,
              breakLabel: opts.breakLabel,
              note: opts.note,
            });
            setAddOpen(false);
            onSessionsChanged?.();
          }}
          onAddPlanned={async (taskId, startedAt, endedAt, note) => {
            const start = new Date(startedAt).getTime();
            const end = new Date(endedAt).getTime();
            const dur = Math.max(0, Math.floor((end - start) / 1000));
            await addPlannedBlock({
              task_id: taskId,
              subtask_id: null,
              start_at: startedAt,
              duration_seconds: dur,
              block_type: 'work',
              notes: note,
            });
            setAddOpen(false);
            onSessionsChanged?.();
          }}
        />
      )}

      {labellingGap && (
        <LabelGapModal
          gap={labellingGap}
          onClose={() => setLabellingGap(null)}
          onConfirm={async (label, note) => {
            // Insert a real tracked_sessions row covering the gap. The auto
            // flag flips false the moment the user confirms — by definition
            // they've now seen it, so it isn't "auto" anymore.
            await addSession(
              null,
              new Date(labellingGap.startMs).toISOString(),
              new Date(labellingGap.endMs).toISOString(),
              {
                blockType: 'break',
                breakLabel: label,
                breakAutoDetected: false,
                note: note,
                // System-detected, user-confirmed gap → not "manually entered"
                // in the audit sense. Honest Score should count this as real.
                manuallyEntered: false,
              },
            );
            setLabellingGap(null);
            onSessionsChanged?.();
          }}
        />
      )}
    </>
  );
}

// Phase 4 — three modes the add-session modal supports. Tracked and Break
// both write to tracked_sessions (differentiated by block_type); Planned
// writes to planned_blocks (the intent table).
type SessionKind = 'tracked' | 'planned' | 'break';

const BREAK_LABELS = [
  { id: 'lunch', label: 'Lunch', icon: '🍱' },
  { id: 'walk', label: 'Walk', icon: '🚶' },
  { id: 'meeting', label: 'Meeting', icon: '👥' },
  { id: 'think', label: 'Think', icon: '💭' },
  { id: 'distract', label: 'Distract', icon: '🌀' },
  { id: 'other', label: 'Other', icon: '…' },
] as const;

// Backfill modal — log a session, planned block, or break after the fact for
// the day currently selected on the Timeline. Phase 4 added the type
// tri-toggle, break-label picker, optional note, and future-date guardrails.
function AddSessionModal({
  dayStart,
  tasks,
  onClose,
  onAdd,
  onAddPlanned,
}: {
  dayStart: Date;
  tasks: { id: string; title: string }[];
  onClose: () => void;
  onAdd: (
    taskId: string | null,
    startedAtISO: string,
    endedAtISO: string,
    opts: {
      blockType: 'tracked' | 'break';
      breakLabel: string | null;
      note: string | null;
    },
  ) => Promise<void>;
  onAddPlanned: (
    taskId: string | null,
    startedAtISO: string,
    endedAtISO: string,
    note: string | null,
  ) => Promise<void>;
}) {
  const defaultStart = useMemo(() => {
    const d = new Date(dayStart);
    d.setHours(12, 0, 0, 0);
    return d.toISOString();
  }, [dayStart]);
  const defaultEnd = useMemo(() => {
    const d = new Date(dayStart);
    d.setHours(13, 0, 0, 0);
    return d.toISOString();
  }, [dayStart]);

  // Is the selected day strictly in the future (vs today / past)?
  const isFutureDay = useMemo(() => {
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return dayStart.getTime() > today.getTime();
  }, [dayStart]);

  // Future dates can ONLY hold planned blocks. Past / today can hold any
  // type. We force the default kind based on the day so the user lands in a
  // valid state without having to think.
  const [kind, setKind] = useState<SessionKind>(
    isFutureDay ? 'planned' : 'tracked',
  );
  const [taskId, setTaskId] = useState<string>('');
  const [startVal, setStartVal] = useState(toLocalInputValue(defaultStart));
  const [endVal, setEndVal] = useState(toLocalInputValue(defaultEnd));
  const [breakLabel, setBreakLabel] = useState<string>('lunch');
  const [breakLabelOther, setBreakLabelOther] = useState<string>('');
  const [note, setNote] = useState<string>('');
  const [err, setErr] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const durationSeconds = useMemo(() => {
    const startISO = fromLocalInputValue(startVal);
    const endISO = fromLocalInputValue(endVal);
    if (!startISO || !endISO) return 0;
    return Math.max(
      0,
      Math.floor((new Date(endISO).getTime() - new Date(startISO).getTime()) / 1000),
    );
  }, [startVal, endVal]);

  const handleSave = async () => {
    setErr(null);
    const startISO = fromLocalInputValue(startVal);
    const endISO = fromLocalInputValue(endVal);
    if (!startISO || !endISO) {
      setErr('Please fill both times.');
      return;
    }
    if (new Date(endISO).getTime() <= new Date(startISO).getTime()) {
      setErr('End must be after start.');
      return;
    }
    // Phase 4 — future-date guard: server-side enforcement isn't built yet,
    // so the client refuses to write a tracked/break row to the future.
    if (isFutureDay && kind !== 'planned') {
      setErr(
        'Future dates can only hold planned blocks. Switch type to Planned.',
      );
      return;
    }
    setBusy(true);
    try {
      if (kind === 'planned') {
        await onAddPlanned(
          taskId || null,
          startISO,
          endISO,
          note.trim() || null,
        );
      } else if (kind === 'break') {
        const finalLabel =
          breakLabel === 'other'
            ? breakLabelOther.trim() || 'other'
            : breakLabel;
        await onAdd(null, startISO, endISO, {
          blockType: 'break',
          breakLabel: finalLabel,
          note: note.trim() || null,
        });
      } else {
        await onAdd(taskId || null, startISO, endISO, {
          blockType: 'tracked',
          breakLabel: null,
          note: note.trim() || null,
        });
      }
    } catch (e) {
      setErr((e as Error).message || 'Save failed.');
      setBusy(false);
    }
  };

  return (
    <div
      className="fixed inset-0 z-40 flex items-center justify-center bg-black/40"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-[14px] p-5 w-[420px] max-w-[92vw] shadow-xl max-h-[92vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="text-[13px] font-extrabold uppercase tracking-[0.5px] text-[#1a1a2e] mb-1">
          Log a session
        </div>
        <div className="text-[12px] text-[#888] mb-3">
          {dayStart.toLocaleDateString('en-IN', {
            weekday: 'long',
            day: 'numeric',
            month: 'short',
            year: 'numeric',
          })}
          {isFutureDay && (
            <span className="ml-2 text-[10px] font-bold uppercase tracking-[0.5px] px-[6px] py-[2px] rounded bg-[#10b98118] text-[#047857]">
              Future · planned only
            </span>
          )}
        </div>

        {/* Phase 4 — manually-entered audit reminder. Always visible so the
            user knows the data here will be flagged in Insights. */}
        <div className="mb-3 p-2 rounded-md bg-[#fef3c7] text-[11px] text-[#78350f] flex items-start gap-2">
          <span aria-hidden>⚠</span>
          <span>
            This entry will be flagged as <b>manually entered</b>. Insights
            (Honest Score) discounts it from your auto-tracked baseline.
          </span>
        </div>

        {/* Phase 4 — type tri-toggle */}
        <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
          Type
        </label>
        <div
          role="radiogroup"
          aria-label="Block type"
          className="grid grid-cols-3 gap-1 mb-3 p-[3px] rounded-lg bg-[#f3f4f6]"
        >
          {(
            [
              {
                id: 'tracked' as const,
                label: 'Tracked',
                desc: 'Actual work',
                disabled: isFutureDay,
              },
              {
                id: 'planned' as const,
                label: 'Planned',
                desc: 'An intent',
                disabled: false,
              },
              {
                id: 'break' as const,
                label: 'Break',
                desc: 'A gap',
                disabled: isFutureDay,
              },
            ]
          ).map((opt) => {
            const on = kind === opt.id;
            return (
              <button
                key={opt.id}
                type="button"
                onClick={() => setKind(opt.id)}
                disabled={opt.disabled}
                role="radio"
                aria-checked={on}
                className="px-2 py-[6px] rounded-[7px] text-[12px] font-bold cursor-pointer transition-colors disabled:opacity-30 disabled:cursor-not-allowed"
                style={{
                  background: on ? '#1a1a2e' : 'transparent',
                  color: on ? '#fff' : '#666',
                }}
                title={opt.desc}
              >
                {opt.label}
              </button>
            );
          })}
        </div>

        {/* Task picker — hidden when type=break (breaks aren't tied to a task) */}
        {kind !== 'break' && (
          <>
            <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
              Task
            </label>
            <select
              value={taskId}
              onChange={(e) => setTaskId(e.target.value)}
              className="w-full mb-3 px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px] bg-white"
            >
              <option value="">— No task (untagged time) —</option>
              {tasks.map((t) => (
                <option key={t.id} value={t.id}>
                  {t.title}
                </option>
              ))}
            </select>
          </>
        )}

        <div className="grid grid-cols-2 gap-2 mb-1">
          <div>
            <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
              Start
            </label>
            <input
              type="datetime-local"
              value={startVal}
              onChange={(e) => setStartVal(e.target.value)}
              className="w-full px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px]"
            />
          </div>
          <div>
            <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
              End
            </label>
            <input
              type="datetime-local"
              value={endVal}
              onChange={(e) => setEndVal(e.target.value)}
              className="w-full px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px]"
            />
          </div>
        </div>
        <div className="text-[10px] text-[#9ca3af] font-mono mb-3">
          Duration: {fmtShort(durationSeconds)}
        </div>

        {/* Break label picker — shown only when type = break */}
        {kind === 'break' && (
          <>
            <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
              Break label
            </label>
            <div className="grid grid-cols-3 gap-1 mb-2">
              {BREAK_LABELS.map((b) => {
                const on = breakLabel === b.id;
                return (
                  <button
                    key={b.id}
                    type="button"
                    onClick={() => setBreakLabel(b.id)}
                    className="px-2 py-[6px] rounded-md text-[12px] font-bold cursor-pointer transition-colors flex items-center justify-center gap-1"
                    style={{
                      background: on ? '#1a1a2e' : '#f3f4f6',
                      color: on ? '#fff' : '#666',
                    }}
                  >
                    <span aria-hidden>{b.icon}</span>
                    {b.label}
                  </button>
                );
              })}
            </div>
            {breakLabel === 'other' && (
              <input
                type="text"
                value={breakLabelOther}
                onChange={(e) => setBreakLabelOther(e.target.value)}
                placeholder="Custom label…"
                className="w-full mb-3 px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px]"
              />
            )}
          </>
        )}

        <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
          Note <span className="font-normal lowercase text-[#bbb]">(optional)</span>
        </label>
        <textarea
          value={note}
          onChange={(e) => setNote(e.target.value)}
          rows={2}
          placeholder="Why retroactively logging? Anything to remember?"
          className="w-full mb-3 px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px] resize-none"
        />

        {err && <div className="text-[11px] text-[#dc2626] mb-2">{err}</div>}

        <div className="flex gap-2 mt-4">
          <div className="flex-1" />
          <button
            onClick={onClose}
            disabled={busy}
            className="px-3 py-2 text-[12px] rounded-md bg-[#f3f4f6] text-[#1a1a2e] hover:bg-[#e5e7eb] disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            onClick={handleSave}
            disabled={busy}
            className="px-3 py-2 text-[12px] font-bold rounded-md bg-[#1a1a2e] text-white hover:opacity-90 disabled:opacity-50"
          >
            Save session
          </button>
        </div>
      </div>
    </div>
  );
}

// Modal for adjusting a single tracked session — edit start/end, change a
// break label, attach a note, or delete the row. Phase 4 added the 30-minute
// "still-recent" safety rule that blocks start/end edits while letting label
// + note edits flow through.
function AdjustSessionModal({
  session,
  taskTitle,
  onClose,
  onStopLive,
  onSave,
  onDelete,
}: {
  session: TrackedSession | null;
  taskTitle: string;
  onClose: () => void;
  onStopLive: () => Promise<void>;
  onSave: (
    startedAtISO: string,
    endedAtISO: string,
    opts: { breakLabel: string | null; note: string | null },
  ) => Promise<void>;
  onDelete: () => Promise<void>;
}) {
  const isLive = !!session && !session.ended_at;
  const fallbackEnd = session
    ? new Date(
        new Date(session.started_at).getTime() +
          ((session.duration_seconds ?? 0) * 1000 || 60 * 60 * 1000),
      ).toISOString()
    : new Date().toISOString();
  const initialStart = session ? toLocalInputValue(session.started_at) : '';
  const initialEnd = session
    ? toLocalInputValue(session.ended_at ?? fallbackEnd)
    : '';
  const initialLabel = session?.break_label ?? 'lunch';
  const initialNote = session?.note ?? '';
  const [startVal, setStartVal] = useState(initialStart);
  const [endVal, setEndVal] = useState(initialEnd);
  // Phase 4 — break label + note are editable even when start/end aren't.
  const [breakLabel, setBreakLabel] = useState<string>(initialLabel);
  const [breakLabelOther, setBreakLabelOther] = useState<string>(
    BREAK_LABELS.some((b) => b.id === initialLabel) ? '' : initialLabel,
  );
  const [note, setNote] = useState<string>(initialNote);
  const [err, setErr] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const isBreak = session?.block_type === 'break';
  const wasManuallyEntered = session?.manually_entered ?? false;

  // Phase 4 — 30-minute safety rule. A session ending less than 30 minutes
  // ago is "still settling" — the live timer may still be the source of
  // truth even after a stop. Block start/end edits on those rows; allow note
  // + label edits because they're metadata-only and useful.
  //
  // Sample "now" once at modal open via a lazy useState initializer (React 19
  // purity rule: no Date.now() during render). The 30-minute threshold is
  // coarse enough that a single snapshot for the modal's lifetime is fine.
  const [openedAtMs] = useState<number>(() => Date.now());
  const minutesSinceEnd =
    session && session.ended_at
      ? (openedAtMs - new Date(session.ended_at).getTime()) / 60_000
      : Number.POSITIVE_INFINITY;
  const recentSettle = minutesSinceEnd < 30;
  const timesLocked = isLive || recentSettle;

  if (!session) return null;

  const handleSave = async () => {
    setErr(null);
    const startISO = fromLocalInputValue(startVal);
    const endISO = fromLocalInputValue(endVal);
    if (!startISO || !endISO) {
      setErr('Please fill both times.');
      return;
    }
    if (new Date(endISO).getTime() <= new Date(startISO).getTime()) {
      setErr('End must be after start.');
      return;
    }
    const finalLabel = isBreak
      ? breakLabel === 'other'
        ? breakLabelOther.trim() || 'other'
        : breakLabel
      : null;
    setBusy(true);
    try {
      await onSave(startISO, endISO, {
        breakLabel: finalLabel,
        note: note.trim() || null,
      });
    } catch (e) {
      setErr((e as Error).message || 'Save failed.');
      setBusy(false);
    }
  };

  return (
    <div
      className="fixed inset-0 z-40 flex items-center justify-center bg-black/40"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-[14px] p-5 w-[420px] max-w-[92vw] shadow-xl max-h-[92vh] overflow-y-auto"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between mb-1">
          <div className="text-[13px] font-extrabold uppercase tracking-[0.5px] text-[#1a1a2e]">
            Adjust {isBreak ? 'break' : 'session'}
          </div>
          {wasManuallyEntered && (
            <span
              className="text-[10px] font-bold uppercase tracking-[0.5px] px-[6px] py-[2px] rounded"
              style={{ background: '#fef3c7', color: '#92400e' }}
              title="This row was created or edited retroactively."
            >
              edited
            </span>
          )}
        </div>
        <div className="text-[12px] text-[#888] mb-3 truncate">{taskTitle}</div>

        {isLive && (
          <div className="mb-3 p-2 rounded-md bg-[#fef3c7] text-[11px] text-[#78350f]">
            This timer is still running. Stop it first, or just delete it.
          </div>
        )}
        {!isLive && recentSettle && (
          <div className="mb-3 p-2 rounded-md bg-[#fef3c7] text-[11px] text-[#78350f]">
            <b>Start / end locked.</b> This session is less than 30 minutes
            old — timer is the source of truth. You can still edit label and
            note. Try again once it settles.
          </div>
        )}
        {!isLive && (
          <div className="mb-3 p-2 rounded-md bg-[#fef3c7] text-[11px] text-[#78350f] flex items-start gap-2">
            <span aria-hidden>⚠</span>
            <span>
              Saving any edit flags this row as <b>manually entered</b> in
              Insights.
            </span>
          </div>
        )}

        <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
          Start
        </label>
        <input
          type="datetime-local"
          value={startVal}
          onChange={(e) => setStartVal(e.target.value)}
          disabled={timesLocked}
          className="w-full mb-3 px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px] disabled:bg-[#f3f4f6]"
        />

        <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
          End
        </label>
        <input
          type="datetime-local"
          value={endVal}
          onChange={(e) => setEndVal(e.target.value)}
          disabled={timesLocked}
          className="w-full mb-3 px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px] disabled:bg-[#f3f4f6]"
        />

        {isBreak && (
          <>
            <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
              Break label
            </label>
            <div className="grid grid-cols-3 gap-1 mb-2">
              {BREAK_LABELS.map((b) => {
                const on = breakLabel === b.id;
                return (
                  <button
                    key={b.id}
                    type="button"
                    onClick={() => setBreakLabel(b.id)}
                    className="px-2 py-[6px] rounded-md text-[12px] font-bold cursor-pointer transition-colors flex items-center justify-center gap-1"
                    style={{
                      background: on ? '#1a1a2e' : '#f3f4f6',
                      color: on ? '#fff' : '#666',
                    }}
                  >
                    <span aria-hidden>{b.icon}</span>
                    {b.label}
                  </button>
                );
              })}
            </div>
            {breakLabel === 'other' && (
              <input
                type="text"
                value={breakLabelOther}
                onChange={(e) => setBreakLabelOther(e.target.value)}
                placeholder="Custom label…"
                className="w-full mb-3 px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px]"
              />
            )}
          </>
        )}

        <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
          Note <span className="font-normal lowercase text-[#bbb]">(optional)</span>
        </label>
        <textarea
          value={note}
          onChange={(e) => setNote(e.target.value)}
          rows={2}
          placeholder="Why edited? Anything to remember?"
          className="w-full mb-3 px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px] resize-none"
        />

        {err && <div className="text-[11px] text-[#dc2626] mb-2">{err}</div>}

        <div className="flex gap-2 mt-4">
          <button
            onClick={onDelete}
            disabled={busy}
            className="px-3 py-2 text-[12px] font-bold rounded-md bg-[#fee2e2] text-[#991b1b] hover:bg-[#fecaca] disabled:opacity-50"
          >
            Delete
          </button>
          <div className="flex-1" />
          <button
            onClick={onClose}
            disabled={busy}
            className="px-3 py-2 text-[12px] rounded-md bg-[#f3f4f6] text-[#1a1a2e] hover:bg-[#e5e7eb] disabled:opacity-50"
          >
            Cancel
          </button>
          {isLive ? (
            <button
              onClick={onStopLive}
              disabled={busy}
              className="px-3 py-2 text-[12px] font-bold rounded-md bg-[#1a1a2e] text-white hover:opacity-90 disabled:opacity-50"
            >
              Stop now
            </button>
          ) : (
            <button
              onClick={handleSave}
              disabled={busy}
              className="px-3 py-2 text-[12px] font-bold rounded-md bg-[#1a1a2e] text-white hover:opacity-90 disabled:opacity-50"
            >
              Save
            </button>
          )}
        </div>
      </div>
    </div>
  );
}

// Phase 5 — quick-label modal for an auto-detected gap. Pre-fills the
// suggested label (italic "auto-detected" tag stays until the user confirms
// per the brief). Smaller than the full edit modal — gaps are quick to triage.
function LabelGapModal({
  gap,
  onClose,
  onConfirm,
}: {
  gap: BlockMeta;
  onClose: () => void;
  onConfirm: (label: string, note: string | null) => Promise<void>;
}) {
  // If the heuristic picked one of the 6 quick labels, default to it; else
  // default to "Lunch" so the user just picks something else if needed.
  const initialLabel = gap.suggestedLabel ?? 'lunch';
  const [label, setLabel] = useState<string>(initialLabel);
  const [labelOther, setLabelOther] = useState<string>('');
  const [note, setNote] = useState<string>('');
  const [busy, setBusy] = useState(false);
  const [err, setErr] = useState<string | null>(null);

  const handleConfirm = async () => {
    setErr(null);
    const final =
      label === 'other' ? labelOther.trim() || 'other' : label;
    setBusy(true);
    try {
      await onConfirm(final, note.trim() || null);
    } catch (e) {
      setErr((e as Error).message || 'Save failed.');
      setBusy(false);
    }
  };

  const startStr = new Date(gap.startMs).toLocaleTimeString('en-IN', {
    hour: '2-digit',
    minute: '2-digit',
  });
  const endStr = new Date(gap.endMs).toLocaleTimeString('en-IN', {
    hour: '2-digit',
    minute: '2-digit',
  });
  const durStr = fmtShort(Math.floor((gap.endMs - gap.startMs) / 1000));

  return (
    <div
      className="fixed inset-0 z-40 flex items-center justify-center bg-black/40"
      onClick={onClose}
    >
      <div
        className="bg-white rounded-[14px] p-5 w-[400px] max-w-[92vw] shadow-xl"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="text-[13px] font-extrabold uppercase tracking-[0.5px] text-[#1a1a2e] mb-1">
          Label this gap
        </div>
        <div className="text-[12px] text-[#888] mb-1">
          {startStr} – {endStr} · {durStr}
        </div>
        {gap.suggestedLabel && (
          <div className="text-[11px] italic text-[#5b3fc8] mb-3">
            Auto-detected suggestion: {gap.suggestedLabel}
          </div>
        )}

        <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
          Label
        </label>
        <div className="grid grid-cols-3 gap-1 mb-2">
          {BREAK_LABELS.map((b) => {
            const on = label === b.id;
            return (
              <button
                key={b.id}
                type="button"
                onClick={() => setLabel(b.id)}
                className="px-2 py-[6px] rounded-md text-[12px] font-bold cursor-pointer transition-colors flex items-center justify-center gap-1"
                style={{
                  background: on ? '#1a1a2e' : '#f3f4f6',
                  color: on ? '#fff' : '#666',
                }}
              >
                <span aria-hidden>{b.icon}</span>
                {b.label}
              </button>
            );
          })}
        </div>
        {label === 'other' && (
          <input
            type="text"
            value={labelOther}
            onChange={(e) => setLabelOther(e.target.value)}
            placeholder="Custom label…"
            className="w-full mb-3 px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px]"
          />
        )}

        <label className="block text-[11px] font-bold uppercase tracking-[0.5px] text-[#888] mb-1">
          Note <span className="font-normal lowercase text-[#bbb]">(optional)</span>
        </label>
        <textarea
          value={note}
          onChange={(e) => setNote(e.target.value)}
          rows={2}
          placeholder="What did you do during this gap?"
          className="w-full mb-3 px-2 py-2 border border-[#e5e7eb] rounded-md text-[13px] resize-none"
        />

        {err && <div className="text-[11px] text-[#dc2626] mb-2">{err}</div>}

        <div className="flex gap-2 mt-2">
          <div className="flex-1" />
          <button
            onClick={onClose}
            disabled={busy}
            className="px-3 py-2 text-[12px] rounded-md bg-[#f3f4f6] text-[#1a1a2e] hover:bg-[#e5e7eb] disabled:opacity-50"
          >
            Cancel
          </button>
          <button
            onClick={handleConfirm}
            disabled={busy}
            className="px-3 py-2 text-[12px] font-bold rounded-md bg-[#1a1a2e] text-white hover:opacity-90 disabled:opacity-50"
          >
            {busy ? 'Saving…' : 'Save break'}
          </button>
        </div>
      </div>
    </div>
  );
}

// <input type="datetime-local"> wants "YYYY-MM-DDTHH:mm" in local time.
// These two helpers round-trip between that and an ISO string.
function toLocalInputValue(iso: string): string {
  const d = new Date(iso);
  const pad = (n: number) => String(n).padStart(2, '0');
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`;
}
function fromLocalInputValue(v: string): string | null {
  if (!v) return null;
  const d = new Date(v);
  if (Number.isNaN(d.getTime())) return null;
  return d.toISOString();
}
